### ISSUE TITLE
Hosting in IIS - Application under 'Default Web Site' - Unable to login

### ISSUE THREAD

**Issue by speddi** [emonney/QuickApp#46]
I created an application under 'Default Web Site' with name 'MyApp'. I am getting an error when trying to login. Some troubleshooting led me to this.

window.location.origin is coming as "http://localhost:8080/" and path as "myapp/login" instead of http://localhost:8080/myapp as the baseUrl.

Utiliites.ts

public static baseUrl() {
if (window.location.origin)
return window.location.origin

    return window.location.protocol + "//" + window.location.hostname + (window.location.port ? ':' + window.location.port : '');
}

**Comment by emonney** [comment]
'window.location.origin is coming as "http://localhost:8080/" and path as "myapp/login" instead of '
This is correct. `location.origin` shouldn't contain path.

Because you're hosting it as a sub application your home address will contain a path.
Either host it as a separate/independent application under IIS or modify the code to return the base url you prefer (i.e. + /myapp).

Closing this. Feel free to reopen if this is still an issue.
