### ISSUE TITLE
roles feature does not seem to work--

### ISSUE THREAD

**Issue by webdev8183** [emonney/QuickApp#54]
I see from reviewing posts that someone else has already reported this, I just wanted to repeat what others have said, this is a great app and I really appreciate the time and effort that went into creating it.
I think i will learn a lot by going through and tinkering with it, and if I ever manage to have a few extra bucks, I will happily donate some money to support your efforts. 

Also if you could add something for how to work with the customers, & orders to the app that would be helpful. I think I can see how it could be done by recreating a lot of the services and just modifying some code here and there, but I don't have a working implementation as every time I make a change it breaks so badly I cannot login, is there anyway to turn that off, so the app will allow me to debug where its failing?

**Comment by emonney** [comment]
Customers, orders, products are placeholders/examples/fictitious pages. The app is a startup template and these business specific functionalities are not implemented by design.

It is advisable to be familiar with the basics of angular (components, services, di, how to make api calls) before using this library.
