### ISSUE TITLE
App crashes in vendor.js at line 5157

### ISSUE THREAD

**Issue by wburchard** [emonney/QuickApp#74]
Using Visual Studio 2017 Professional, running on Windows 7 x64.  Created a new project after downloading and installing version 2.5.1.  Installed Node 8.9.3.  Installed Angular CLI 1.6.3.  Successfully compiled project.  When I attempt to run the project, I see the 'application loading' splash screen, but it then crashes with the following error:

JavaScript critical error at line 5157, column 1 in http://localhost:51407/dist/vendor.js?v=KTbG8orBqXYcqt1brf70VwUoUxlTF_bMfvrXbFAFMCo\n\nSCRIPT1028: Expected identifier, string or number

![image](https://user-images.githubusercontent.com/2690384/34537710-686f7064-f097-11e7-8f14-846f741330e0.png)

**Comment by emonney** [comment]
Is this a vanilla installation? Delete the below folders, restart visual studio, rebuild solution and post your response back.

Delete the dist folder: wwwroot > dist
Delete node_modules folder

If this is for support rather than reporting a bug, please move this post to the [support forum](http://www.ebenmonney.com/forum/?view=forum&id=14).
Github issues will only be used for bug reporting
